package program.metode.simplex;
public class MetodeSimplex extends javax.swing.JFrame {
    //buat variabel program linear
    float kendalaW1, kendalaW2, kendalaW3,
            kendalaX1, kendalaX2, kendalaX3,
            kendalaY1, kendalaY2, kendalaY3,
            kendalaNk1, kendalaNk2, kendalaNk3,
            tujuanW, tujuanX, tujuanY;
    //buat variabel tabel simplex
    int banyakIterasi = 10;
    String[] bv1 = new String[banyakIterasi], bv2 = new String[banyakIterasi], bv3 = new String[banyakIterasi], bv4 = new String[banyakIterasi];
    float[] tabelZ1 = new float[banyakIterasi], tabelZ2 = new float[banyakIterasi], tabelZ3 = new float[banyakIterasi], tabelZ4 = new float[banyakIterasi],
            tabelW1 = new float[banyakIterasi], tabelW2 = new float[banyakIterasi], tabelW3 = new float[banyakIterasi], tabelW4 = new float[banyakIterasi],
            tabelX1 = new float[banyakIterasi], tabelX2 = new float[banyakIterasi], tabelX3 = new float[banyakIterasi], tabelX4 = new float[banyakIterasi],
            tabelY1 = new float[banyakIterasi], tabelY2 = new float[banyakIterasi], tabelY3 = new float[banyakIterasi], tabelY4 = new float[banyakIterasi],
            tabelS11 = new float[banyakIterasi], tabelS12 = new float[banyakIterasi], tabelS13 = new float[banyakIterasi], tabelS14 = new float[banyakIterasi],
            tabelS21 = new float[banyakIterasi], tabelS22 = new float[banyakIterasi], tabelS23 = new float[banyakIterasi], tabelS24 = new float[banyakIterasi],
            tabelS31 = new float[banyakIterasi], tabelS32 = new float[banyakIterasi], tabelS33 = new float[banyakIterasi], tabelS34 = new float[banyakIterasi],
            tabelNk1 = new float[banyakIterasi], tabelNk2 = new float[banyakIterasi], tabelNk3 = new float[banyakIterasi], tabelNk4 = new float[banyakIterasi];
    int iterasi;
    float[] pivot = new float[banyakIterasi];
    String[] ev = new String[banyakIterasi], lv = new String[banyakIterasi];
    public MetodeSimplex() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tf_tujuan_w = new javax.swing.JTextField();
        tf_kendala_nk_1 = new javax.swing.JTextField();
        tf_kendala_x_3 = new javax.swing.JTextField();
        tf_kendala_nk_2 = new javax.swing.JTextField();
        tf_kendala_y_3 = new javax.swing.JTextField();
        tf_kendala_nk_3 = new javax.swing.JTextField();
        tf_kendala_y_2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tf_kendala_w_3 = new javax.swing.JTextField();
        tf_kendala_w_2 = new javax.swing.JTextField();
        tf_kendala_x_2 = new javax.swing.JTextField();
        tf_kendala_x_1 = new javax.swing.JTextField();
        tf_kendala_y_1 = new javax.swing.JTextField();
        tf_tujuan_y = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tf_tujuan_x = new javax.swing.JTextField();
        tf_kendala_w_1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_baku = new javax.swing.JTextArea();
        bt_baku = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        tf_hasil_z = new javax.swing.JTextField();
        tf_hasil_w = new javax.swing.JTextField();
        tf_hasil_x = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tf_iterasi = new javax.swing.JTextField();
        bt_iterasi_back = new javax.swing.JButton();
        bt_iterasi_next = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        tf_tabel_bv_1 = new javax.swing.JTextField();
        tf_tabel_bv_2 = new javax.swing.JTextField();
        tf_tabel_bv_3 = new javax.swing.JTextField();
        tf_tabel_bv_4 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tf_tabel_z_1 = new javax.swing.JTextField();
        tf_tabel_z_2 = new javax.swing.JTextField();
        tf_tabel_z_3 = new javax.swing.JTextField();
        tf_tabel_z_4 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        tf_pivot = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        tf_hasil_y = new javax.swing.JTextField();
        tf_hasil_s1 = new javax.swing.JTextField();
        tf_hasil_s2 = new javax.swing.JTextField();
        tf_hasil_s3 = new javax.swing.JTextField();
        tf_tabel_w_1 = new javax.swing.JTextField();
        tf_tabel_w_2 = new javax.swing.JTextField();
        tf_tabel_w_3 = new javax.swing.JTextField();
        tf_tabel_w_4 = new javax.swing.JTextField();
        tf_tabel_x_1 = new javax.swing.JTextField();
        tf_tabel_x_2 = new javax.swing.JTextField();
        tf_tabel_x_3 = new javax.swing.JTextField();
        tf_tabel_x_4 = new javax.swing.JTextField();
        tf_tabel_y_1 = new javax.swing.JTextField();
        tf_tabel_y_2 = new javax.swing.JTextField();
        tf_tabel_y_3 = new javax.swing.JTextField();
        tf_tabel_y_4 = new javax.swing.JTextField();
        tf_tabel_s1_1 = new javax.swing.JTextField();
        tf_tabel_s1_2 = new javax.swing.JTextField();
        tf_tabel_s1_3 = new javax.swing.JTextField();
        tf_tabel_s1_4 = new javax.swing.JTextField();
        tf_tabel_s2_1 = new javax.swing.JTextField();
        tf_tabel_s2_2 = new javax.swing.JTextField();
        tf_tabel_s2_3 = new javax.swing.JTextField();
        tf_tabel_s2_4 = new javax.swing.JTextField();
        tf_tabel_s3_1 = new javax.swing.JTextField();
        tf_tabel_s3_2 = new javax.swing.JTextField();
        tf_tabel_s3_3 = new javax.swing.JTextField();
        tf_tabel_s3_4 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        tf_tabel_nk_1 = new javax.swing.JTextField();
        tf_tabel_nk_2 = new javax.swing.JTextField();
        tf_tabel_nk_3 = new javax.swing.JTextField();
        tf_tabel_nk_4 = new javax.swing.JTextField();
        bt_simplex = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel8.setText("Total Waktu");

        jLabel1.setText("Produk A");

        jLabel5.setText("Proses 2");

        jLabel4.setText("Proses 1");

        jLabel3.setText("Produk C");

        jLabel2.setText("Produk B");

        jLabel7.setText("Biaya Produksi");

        jLabel6.setText("Proses 3");

        ta_baku.setColumns(20);
        ta_baku.setRows(5);
        jScrollPane1.setViewportView(ta_baku);

        bt_baku.setText("Bentuk Baku");
        bt_baku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_bakuActionPerformed(evt);
            }
        });

        jLabel9.setText("Hasil");

        tf_hasil_z.setText("0");

        tf_hasil_w.setText("0");
        tf_hasil_w.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_hasil_wActionPerformed(evt);
            }
        });

        tf_hasil_x.setText("0");

        jLabel10.setText("Proses");

        jLabel11.setText("Iterasi");

        tf_iterasi.setText("0");

        bt_iterasi_back.setText(" < ");
        bt_iterasi_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_iterasi_backActionPerformed(evt);
            }
        });

        bt_iterasi_next.setText(" > ");
        bt_iterasi_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_iterasi_nextActionPerformed(evt);
            }
        });

        jLabel12.setText("BV");

        tf_tabel_bv_1.setText("Z");

        tf_tabel_bv_2.setText("S1");

        tf_tabel_bv_3.setText("S2");

        tf_tabel_bv_4.setText("S3");

        jLabel13.setText("Z");

        tf_tabel_z_1.setText("0");

        tf_tabel_z_2.setText("0");

        tf_tabel_z_3.setText("0");

        tf_tabel_z_4.setText("0");

        jLabel14.setText("W");

        jLabel15.setText("X");

        jLabel16.setText("Y");

        jLabel17.setText("S1");

        jLabel19.setText("S3");

        jLabel20.setText("NK");

        jLabel21.setText("Pivot");

        tf_pivot.setText("0");

        jLabel22.setText("Z");

        jLabel23.setText("W");

        jLabel24.setText("X");

        jLabel25.setText("Y");

        jLabel26.setText("S1");

        jLabel27.setText("S2");

        jLabel28.setText("S3");

        tf_hasil_y.setText("0");

        tf_hasil_s1.setText("0");

        tf_hasil_s2.setText("0");

        tf_hasil_s3.setText("0");

        tf_tabel_w_1.setText("0");

        tf_tabel_w_2.setText("0");

        tf_tabel_w_3.setText("0");

        tf_tabel_w_4.setText("0");

        tf_tabel_x_1.setText("0");

        tf_tabel_x_2.setText("0");

        tf_tabel_x_3.setText("0");

        tf_tabel_x_4.setText("0");

        tf_tabel_y_1.setText("0");

        tf_tabel_y_2.setText("0");

        tf_tabel_y_3.setText("0");

        tf_tabel_y_4.setText("0");

        tf_tabel_s1_1.setText("0");

        tf_tabel_s1_2.setText("0");

        tf_tabel_s1_3.setText("0");

        tf_tabel_s1_4.setText("0");

        tf_tabel_s2_1.setText("0");

        tf_tabel_s2_2.setText("0");

        tf_tabel_s2_3.setText("0");

        tf_tabel_s2_4.setText("0");

        tf_tabel_s3_1.setText("0");

        tf_tabel_s3_2.setText("0");

        tf_tabel_s3_3.setText("0");

        tf_tabel_s3_4.setText("0");

        jLabel29.setText("S2");

        tf_tabel_nk_1.setText("0");

        tf_tabel_nk_2.setText("0");

        tf_tabel_nk_3.setText("0");

        tf_tabel_nk_4.setText("0");

        bt_simplex.setText("Tabel Simplex");
        bt_simplex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_simplexActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(tf_pivot, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel22)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tf_hasil_z, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tf_hasil_w, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                                            .addComponent(tf_hasil_x)
                                            .addComponent(tf_hasil_y))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel26)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tf_hasil_s1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel28)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tf_hasil_s3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel27)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tf_hasil_s2)))))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel7))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tf_kendala_nk_1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tf_kendala_nk_2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tf_kendala_nk_3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(tf_kendala_y_1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tf_kendala_y_2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tf_kendala_y_3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(tf_tujuan_y, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(tf_kendala_w_1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(tf_kendala_w_2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(tf_kendala_w_3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(tf_tujuan_w, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(tf_kendala_x_1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(tf_kendala_x_2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(tf_kendala_x_3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(tf_tujuan_x)))))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt_baku)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt_simplex))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bt_iterasi_back)
                                    .addComponent(jLabel11)
                                    .addComponent(tf_iterasi, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bt_iterasi_next))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_tabel_bv_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12)
                                    .addComponent(tf_tabel_bv_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_tabel_bv_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_tabel_bv_1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel13)
                                    .addComponent(tf_tabel_z_1, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                                    .addComponent(tf_tabel_z_2)
                                    .addComponent(tf_tabel_z_3)
                                    .addComponent(tf_tabel_z_4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel14)
                                    .addComponent(tf_tabel_w_1, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                                    .addComponent(tf_tabel_w_2)
                                    .addComponent(tf_tabel_w_3)
                                    .addComponent(tf_tabel_w_4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel15)
                                    .addComponent(tf_tabel_x_1, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                                    .addComponent(tf_tabel_x_2)
                                    .addComponent(tf_tabel_x_3)
                                    .addComponent(tf_tabel_x_4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel16)
                                    .addComponent(tf_tabel_y_1, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                                    .addComponent(tf_tabel_y_2)
                                    .addComponent(tf_tabel_y_3)
                                    .addComponent(tf_tabel_y_4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tf_tabel_s1_1, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                            .addComponent(tf_tabel_s1_2)
                                            .addComponent(tf_tabel_s1_3)
                                            .addComponent(tf_tabel_s1_4))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(tf_tabel_s2_1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel29))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel19)
                                                        .addGap(18, 18, 18))
                                                    .addComponent(tf_tabel_s3_1, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(tf_tabel_s2_3, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                                                    .addComponent(tf_tabel_s2_2)
                                                    .addComponent(tf_tabel_s2_4))
                                                .addGap(12, 12, 12)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(tf_tabel_s3_2)
                                                    .addComponent(tf_tabel_s3_4)
                                                    .addComponent(tf_tabel_s3_3)))))
                                    .addComponent(jLabel17))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tf_tabel_nk_1, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                                        .addComponent(tf_tabel_nk_2)
                                        .addComponent(tf_tabel_nk_3)
                                        .addComponent(tf_tabel_nk_4)))))
                        .addGap(26, 26, 26))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_kendala_w_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_kendala_w_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_kendala_w_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_tujuan_w, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tf_kendala_x_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tf_kendala_x_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tf_kendala_x_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tf_tujuan_x, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_kendala_y_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_kendala_y_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_kendala_y_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_tujuan_y, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_kendala_nk_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_kendala_nk_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_kendala_nk_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(bt_baku)
                    .addComponent(bt_simplex))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(5, 5, 5)
                                .addComponent(bt_iterasi_back))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(5, 5, 5)
                                .addComponent(tf_tabel_bv_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_iterasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_tabel_bv_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_iterasi_next)
                            .addComponent(tf_tabel_bv_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_tabel_bv_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(5, 5, 5)
                        .addComponent(tf_tabel_z_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_tabel_z_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_tabel_z_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_tabel_z_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel29)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tf_tabel_w_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_tabel_w_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_tabel_w_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_tabel_w_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tf_tabel_x_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_tabel_x_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_tabel_x_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_tabel_x_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tf_tabel_y_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_tabel_y_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_tabel_y_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_tabel_y_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tf_tabel_s1_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_tabel_s2_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_tabel_s1_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_tabel_s1_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_tabel_s1_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tf_tabel_nk_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_tabel_s3_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(41, 41, 41)
                                .addComponent(tf_tabel_nk_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_tabel_nk_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tf_tabel_s2_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_tabel_s3_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_tabel_nk_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tf_tabel_s2_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_tabel_s3_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tf_tabel_s2_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_tabel_s3_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_hasil_z, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22)
                            .addComponent(tf_pivot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_hasil_w, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23)
                            .addComponent(jLabel26)
                            .addComponent(tf_hasil_s1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_hasil_x, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24)
                            .addComponent(jLabel27)
                            .addComponent(tf_hasil_s2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_hasil_y, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(jLabel28)
                    .addComponent(tf_hasil_s3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_bakuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_bakuActionPerformed
        // TODO add your handling code here:
        //isi variabel program linear
        kendalaW1 = Float.parseFloat(tf_kendala_w_1.getText());
        kendalaW2 = Float.parseFloat(tf_kendala_w_2.getText());
        kendalaW3 = Float.parseFloat(tf_kendala_w_3.getText());
        kendalaX1 = Float.parseFloat(tf_kendala_x_1.getText());
        kendalaX2 = Float.parseFloat(tf_kendala_x_2.getText());
        kendalaX3 = Float.parseFloat(tf_kendala_x_3.getText());
        kendalaY1 = Float.parseFloat(tf_kendala_y_1.getText());
        kendalaY2 = Float.parseFloat(tf_kendala_y_2.getText());
        kendalaY3 = Float.parseFloat(tf_kendala_y_3.getText());
        kendalaNk1= Float.parseFloat(tf_kendala_nk_1.getText());
        kendalaNk2= Float.parseFloat(tf_kendala_nk_2.getText());
        kendalaNk3= Float.parseFloat(tf_kendala_nk_3.getText());
        tujuanW   = Float.parseFloat(tf_tujuan_w.getText());
        tujuanX   = Float.parseFloat(tf_tujuan_x.getText());
        tujuanY   = Float.parseFloat(tf_tujuan_y.getText());
        //menampilkan bentuk program linear
        String textBaku;
        textBaku = "Fungsi kendala :\n";
        textBaku += kendalaW1+"w + "+kendalaX1+"x + "+kendalaY1+"y <= "+kendalaNk1+"\n";
        textBaku += kendalaW2+"w + "+kendalaX2+"x + "+kendalaY2+"y <= "+kendalaNk2+"\n";
        textBaku += kendalaW3+"w + "+kendalaX3+"x + "+kendalaY3+"y <= "+kendalaNk3+"\n";
        textBaku += "Fungsi Tujuan :\n";
        textBaku += "maxZ = "+tujuanW+"w + "+tujuanX+"x + "+tujuanY+"y";
        //TODO menampilkan bentuk baku
        textBaku += "\n\n================================================================\n";
        textBaku += "Bentuk Baku :\n";
        textBaku += kendalaW1+"w + "+kendalaX1+"x + "+kendalaY1+"y + s1 = "+kendalaNk1+"\n";
        textBaku += kendalaW2+"w + "+kendalaX2+"x + "+kendalaY2+"y + s2 = "+kendalaNk2+"\n";
        textBaku += kendalaW3+"w + "+kendalaX3+"x + "+kendalaY3+"y + s3 = "+kendalaNk3+"\n";
        textBaku += "Z - "+tujuanW+"w - "+tujuanX+"x - "+tujuanY+"y - 0s1 - 0s2 - 0s3 = 0";
        ta_baku.setText(textBaku);
    }//GEN-LAST:event_bt_bakuActionPerformed

    private void bt_simplexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_simplexActionPerformed
        hitungTabelSimplex();
        tampilkanHasil();
    }//GEN-LAST:event_bt_simplexActionPerformed

    private void bt_iterasi_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_iterasi_backActionPerformed
        //tombol <<
        int posisi;
        posisi = Integer.parseInt(tf_iterasi.getText().toString());
        System.out.println("posisi : "+posisi);
        if (posisi>0) {
            updateIsiTabel(posisi-1);
            tf_iterasi.setText(posisi-1+"");
            tf_pivot.setText(pivot[posisi-1]+"");
        }
    }//GEN-LAST:event_bt_iterasi_backActionPerformed

    private void bt_iterasi_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_iterasi_nextActionPerformed
        //tombol >
        int posisi;
        posisi = Integer.parseInt(tf_iterasi.getText().toString());
        System.out.println("posisi : "+posisi);
        if (posisi<iterasi) {
            updateIsiTabel(posisi+1);
            tf_iterasi.setText((posisi+1)+"");
            tf_pivot.setText(pivot[posisi+1]+"");
        }
    }//GEN-LAST:event_bt_iterasi_nextActionPerformed

    private void tf_hasil_wActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_hasil_wActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_hasil_wActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MetodeSimplex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MetodeSimplex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MetodeSimplex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MetodeSimplex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MetodeSimplex().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_baku;
    private javax.swing.JButton bt_iterasi_back;
    private javax.swing.JButton bt_iterasi_next;
    private javax.swing.JButton bt_simplex;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea ta_baku;
    private javax.swing.JTextField tf_hasil_s1;
    private javax.swing.JTextField tf_hasil_s2;
    private javax.swing.JTextField tf_hasil_s3;
    private javax.swing.JTextField tf_hasil_w;
    private javax.swing.JTextField tf_hasil_x;
    private javax.swing.JTextField tf_hasil_y;
    private javax.swing.JTextField tf_hasil_z;
    private javax.swing.JTextField tf_iterasi;
    private javax.swing.JTextField tf_kendala_nk_1;
    private javax.swing.JTextField tf_kendala_nk_2;
    private javax.swing.JTextField tf_kendala_nk_3;
    private javax.swing.JTextField tf_kendala_w_1;
    private javax.swing.JTextField tf_kendala_w_2;
    private javax.swing.JTextField tf_kendala_w_3;
    private javax.swing.JTextField tf_kendala_x_1;
    private javax.swing.JTextField tf_kendala_x_2;
    private javax.swing.JTextField tf_kendala_x_3;
    private javax.swing.JTextField tf_kendala_y_1;
    private javax.swing.JTextField tf_kendala_y_2;
    private javax.swing.JTextField tf_kendala_y_3;
    private javax.swing.JTextField tf_pivot;
    private javax.swing.JTextField tf_tabel_bv_1;
    private javax.swing.JTextField tf_tabel_bv_2;
    private javax.swing.JTextField tf_tabel_bv_3;
    private javax.swing.JTextField tf_tabel_bv_4;
    private javax.swing.JTextField tf_tabel_nk_1;
    private javax.swing.JTextField tf_tabel_nk_2;
    private javax.swing.JTextField tf_tabel_nk_3;
    private javax.swing.JTextField tf_tabel_nk_4;
    private javax.swing.JTextField tf_tabel_s1_1;
    private javax.swing.JTextField tf_tabel_s1_2;
    private javax.swing.JTextField tf_tabel_s1_3;
    private javax.swing.JTextField tf_tabel_s1_4;
    private javax.swing.JTextField tf_tabel_s2_1;
    private javax.swing.JTextField tf_tabel_s2_2;
    private javax.swing.JTextField tf_tabel_s2_3;
    private javax.swing.JTextField tf_tabel_s2_4;
    private javax.swing.JTextField tf_tabel_s3_1;
    private javax.swing.JTextField tf_tabel_s3_2;
    private javax.swing.JTextField tf_tabel_s3_3;
    private javax.swing.JTextField tf_tabel_s3_4;
    private javax.swing.JTextField tf_tabel_w_1;
    private javax.swing.JTextField tf_tabel_w_2;
    private javax.swing.JTextField tf_tabel_w_3;
    private javax.swing.JTextField tf_tabel_w_4;
    private javax.swing.JTextField tf_tabel_x_1;
    private javax.swing.JTextField tf_tabel_x_2;
    private javax.swing.JTextField tf_tabel_x_3;
    private javax.swing.JTextField tf_tabel_x_4;
    private javax.swing.JTextField tf_tabel_y_1;
    private javax.swing.JTextField tf_tabel_y_2;
    private javax.swing.JTextField tf_tabel_y_3;
    private javax.swing.JTextField tf_tabel_y_4;
    private javax.swing.JTextField tf_tabel_z_1;
    private javax.swing.JTextField tf_tabel_z_2;
    private javax.swing.JTextField tf_tabel_z_3;
    private javax.swing.JTextField tf_tabel_z_4;
    private javax.swing.JTextField tf_tujuan_w;
    private javax.swing.JTextField tf_tujuan_x;
    private javax.swing.JTextField tf_tujuan_y;
    // End of variables declaration//GEN-END:variables

    //mencari nilai pivot
    private void cariPivot(int iterasi) {
        //mencari ev
        cariEv(iterasi);
        //mencari lv
        cariLv(iterasi);
        //menggunakan nilai ev dan lv untuk mencari pivot
        if (ev[iterasi]=="w") {
            if (lv[iterasi]=="2") {
                pivot[iterasi]=tabelW2[iterasi];
            }else if (lv[iterasi]=="3") {
                pivot[iterasi]=tabelW3[iterasi];
            }else if (lv[iterasi]=="4") {
                pivot[iterasi]=tabelW4[iterasi];
            }
        } else if (ev[iterasi]=="x") {
            if (lv[iterasi]=="2") {
                pivot[iterasi]=tabelX2[iterasi];
            }else if (lv[iterasi]=="3") {
                pivot[iterasi]=tabelX3[iterasi];
            }else if (lv[iterasi]=="4") {
                pivot[iterasi]=tabelX4[iterasi];
            }
        } else if (ev[iterasi]=="y") {
            if (lv[iterasi]=="2") {
                pivot[iterasi]=tabelY2[iterasi];
            }else if (lv[iterasi]=="3") {
                pivot[iterasi]=tabelY3[iterasi];
            }else if (lv[iterasi]=="4") {
                pivot[iterasi]=tabelY4[iterasi];
            }
        }else{
            pivot[iterasi]=0;
        }
        System.out.println("pivot iterasi " + iterasi + " : "+pivot[iterasi]);
    }

    private void cariEv(int iterasi) {
        //mencari nilai ev terkecil
        float terkecil;
        if (tabelW1[iterasi]<0 || tabelX1[iterasi]<0 || tabelY1[iterasi]<0) {
            if (tabelW1[iterasi]<=tabelX1[iterasi] && tabelW1[iterasi]<=tabelY1[iterasi]) {
                ev[iterasi]="w";
            }else if (tabelX1[iterasi]<=tabelW1[iterasi] && tabelX1[iterasi]<=tabelY1[iterasi]) {
                ev[iterasi]="x";
            }else if (tabelY1[iterasi]<=tabelW1[iterasi] && tabelY1[iterasi]<=tabelX1[iterasi]) {
                ev[iterasi]="y";
            }
        }else{
            ev[iterasi]=null;
        }
        System.out.println("ev iterasi "+iterasi+" : "+ev[iterasi]);
    }

    //cari baris lv
    private void cariLv(int iterasi) {
        float periksaLv2=0,
                periksaLv3=0,
                periksaLv4=0;
        if (ev[iterasi]=="w") {
            periksaLv2 = tabelNk2[iterasi]/tabelW2[iterasi];
            periksaLv3 = tabelNk3[iterasi]/tabelW3[iterasi];
            periksaLv4 = tabelNk4[iterasi]/tabelW4[iterasi];
        } else if (ev[iterasi]=="x") {
            periksaLv2 = tabelNk2[iterasi]/tabelX2[iterasi];
            periksaLv3 = tabelNk3[iterasi]/tabelX3[iterasi];
            periksaLv4 = tabelNk4[iterasi]/tabelX4[iterasi];
        } else if (ev[iterasi]=="y") {
            periksaLv2 = tabelNk2[iterasi]/tabelY2[iterasi];
            periksaLv3 = tabelNk3[iterasi]/tabelY3[iterasi];
            periksaLv4 = tabelNk4[iterasi]/tabelY4[iterasi];
        }
        if (periksaLv2<periksaLv3 && periksaLv2<periksaLv4) {
            lv[iterasi]="2";
        } else if (periksaLv3<periksaLv2 && periksaLv3<periksaLv4) {
            lv[iterasi]="3";
        } else if (periksaLv4<periksaLv3 && periksaLv4<periksaLv2) {
            lv[iterasi]="4";
        }
        System.out.println("lv iterasi "+iterasi+" : "+lv[iterasi]);
    }

    private void updateIsiTabel(int iterasi) {
        tf_tabel_bv_1.setText(bv1[iterasi]);
        tf_tabel_bv_2.setText(bv2[iterasi]);
        tf_tabel_bv_3.setText(bv3[iterasi]);
        tf_tabel_bv_4.setText(bv4[iterasi]);
        tf_tabel_z_1.setText(tabelZ1[iterasi]+"");
        tf_tabel_z_2.setText(tabelZ2[iterasi]+"");
        tf_tabel_z_3.setText(tabelZ3[iterasi]+"");
        tf_tabel_z_4.setText(tabelZ4[iterasi]+"");
        tf_tabel_w_1.setText(tabelW1[iterasi]+"");
        tf_tabel_w_2.setText(tabelW2[iterasi]+"");
        tf_tabel_w_3.setText(tabelW3[iterasi]+"");
        tf_tabel_w_4.setText(tabelW4[iterasi]+"");
        tf_tabel_x_1.setText(tabelX1[iterasi]+"");
        tf_tabel_x_2.setText(tabelX2[iterasi]+"");
        tf_tabel_x_3.setText(tabelX3[iterasi]+"");
        tf_tabel_x_4.setText(tabelX4[iterasi]+"");
        tf_tabel_y_1.setText(tabelY1[iterasi]+"");
        tf_tabel_y_2.setText(tabelY2[iterasi]+"");
        tf_tabel_y_3.setText(tabelY3[iterasi]+"");
        tf_tabel_y_4.setText(tabelY4[iterasi]+"");
        tf_tabel_s1_1.setText(tabelS11[iterasi]+"");
        tf_tabel_s1_2.setText(tabelS12[iterasi]+"");
        tf_tabel_s1_3.setText(tabelS13[iterasi]+"");
        tf_tabel_s1_4.setText(tabelS14[iterasi]+"");
        tf_tabel_s2_1.setText(tabelS21[iterasi]+"");
        tf_tabel_s2_2.setText(tabelS22[iterasi]+"");
        tf_tabel_s2_3.setText(tabelS23[iterasi]+"");
        tf_tabel_s2_4.setText(tabelS24[iterasi]+"");
        tf_tabel_s3_1.setText(tabelS31[iterasi]+"");
        tf_tabel_s3_2.setText(tabelS32[iterasi]+"");
        tf_tabel_s3_3.setText(tabelS33[iterasi]+"");
        tf_tabel_s3_4.setText(tabelS34[iterasi]+"");
        tf_tabel_nk_1.setText(tabelNk1[iterasi]+"");
        tf_tabel_nk_2.setText(tabelNk2[iterasi]+"");
        tf_tabel_nk_3.setText(tabelNk3[iterasi]+"");
        tf_tabel_nk_4.setText(tabelNk4[iterasi]+"");
    }

    private void iterasiNol() {
        //memasukan nilai ke tabel simplex iterasi 0
        bv1[0]="Z";
        bv2[0]="s1";
        bv3[0]="s2";
        bv4[0]="s3";
        tabelZ1[0]=1;
        tabelZ2[0]=0;
        tabelZ3[0]=0;
        tabelZ4[0]=0;
        tabelW1[0]=tujuanW*(-1);
        tabelW2[0]=kendalaW1;
        tabelW3[0]=kendalaW2;
        tabelW4[0]=kendalaW3;
        tabelX1[0]=tujuanX*(-1);
        tabelX2[0]=kendalaX1;
        tabelX3[0]=kendalaX2;
        tabelX4[0]=kendalaX3;
        tabelY1[0]=tujuanY*(-1);
        tabelY2[0]=kendalaY1;
        tabelY3[0]=kendalaY2;
        tabelY4[0]=kendalaY3;
        tabelS11[0]=0;
        tabelS12[0]=1;
        tabelS13[0]=0;
        tabelS14[0]=0;
        tabelS21[0]=0;
        tabelS22[0]=1;
        tabelS23[0]=0;
        tabelS24[0]=0;
        tabelS31[0]=0;
        tabelS32[0]=1;
        tabelS33[0]=0;
        tabelS34[0]=0;
        tabelNk1[0]=0;
        tabelNk2[0]=kendalaNk1;
        tabelNk3[0]=kendalaNk2;
        tabelNk4[0]=kendalaNk3;
    }
    
    private void operasiBaris(int iterasi){
        //test
        System.out.println("iterasi "+iterasi);
        if (lv[iterasi-1]=="2") {
            //baris pivot
            tabelZ2[iterasi]=barisPivot(tabelZ2[iterasi-1], iterasi);
            tabelW2[iterasi]=barisPivot(tabelW2[iterasi-1], iterasi);
            tabelX2[iterasi]=barisPivot(tabelX2[iterasi-1], iterasi);
            tabelY2[iterasi]=barisPivot(tabelY2[iterasi-1], iterasi);
            tabelS12[iterasi]=barisPivot(tabelS12[iterasi-1], iterasi);
            tabelS22[iterasi]=barisPivot(tabelS22[iterasi-1], iterasi);
            tabelS32[iterasi]=barisPivot(tabelS32[iterasi-1], iterasi);
            tabelNk2[iterasi]=barisPivot(tabelNk2[iterasi-1], iterasi);
            //baris non pivot
            if (ev[iterasi-1]=="w") {
                //isi bv
                bv1[iterasi]=bv1[iterasi-1];
                bv2[iterasi]="W";
                bv3[iterasi]=bv3[iterasi-1];
                bv4[iterasi]=bv4[iterasi-1];
                //baris 1
                tabelW1[iterasi] = tabelW1[iterasi-1] - tabelW1[iterasi-1] * tabelW2[iterasi];
                tabelZ1[iterasi] = tabelZ1[iterasi-1] - tabelW1[iterasi-1] * tabelZ2[iterasi];
                tabelX1[iterasi] = tabelX1[iterasi-1] - tabelW1[iterasi-1] * tabelX2[iterasi];
                tabelY1[iterasi] = tabelY1[iterasi-1] - tabelW1[iterasi-1] * tabelY2[iterasi];
                tabelS11[iterasi] =tabelS11[iterasi-1] - tabelW1[iterasi-1] * tabelS12[iterasi];
                tabelS21[iterasi] =tabelS21[iterasi-1] - tabelW1[iterasi-1] * tabelS22[iterasi];
                tabelS31[iterasi] =tabelS31[iterasi-1] - tabelW1[iterasi-1] * tabelS32[iterasi];
                tabelNk1[iterasi] =tabelNk1[iterasi-1] - tabelW1[iterasi-1] * tabelNk2[iterasi];
                //baris 3
                tabelW3[iterasi] = tabelW3[iterasi-1] - tabelW3[iterasi-1] * tabelW2[iterasi];
                tabelZ3[iterasi] = tabelZ3[iterasi-1] - tabelW3[iterasi-1] * tabelZ2[iterasi];
                tabelX3[iterasi] = tabelX3[iterasi-1] - tabelW3[iterasi-1] * tabelX2[iterasi];
                tabelY3[iterasi] = tabelY3[iterasi-1] - tabelW3[iterasi-1] * tabelY2[iterasi];
                tabelS13[iterasi] =tabelS13[iterasi-1] - tabelW3[iterasi-1] * tabelS12[iterasi];
                tabelS23[iterasi] =tabelS23[iterasi-1] - tabelW3[iterasi-1] * tabelS22[iterasi];
                tabelS33[iterasi] =tabelS33[iterasi-1] - tabelW3[iterasi-1] * tabelS32[iterasi];
                tabelNk3[iterasi] =tabelNk3[iterasi-1] - tabelW3[iterasi-1] * tabelNk2[iterasi];
                //baris 4
                tabelW4[iterasi] = tabelW4[iterasi-1] - tabelW4[iterasi-1] * tabelW2[iterasi];
                tabelZ4[iterasi] = tabelZ4[iterasi-1] - tabelW4[iterasi-1] * tabelZ2[iterasi];
                tabelX4[iterasi] = tabelX4[iterasi-1] - tabelW4[iterasi-1] * tabelX2[iterasi];
                tabelY4[iterasi] = tabelY4[iterasi-1] - tabelW4[iterasi-1] * tabelY2[iterasi];
                tabelS14[iterasi] =tabelS14[iterasi-1] - tabelW4[iterasi-1] * tabelS12[iterasi];
                tabelS24[iterasi] =tabelS24[iterasi-1] - tabelW4[iterasi-1] * tabelS22[iterasi];
                tabelS34[iterasi] =tabelS34[iterasi-1] - tabelW4[iterasi-1] * tabelS32[iterasi];
                tabelNk4[iterasi] =tabelNk4[iterasi-1] - tabelW4[iterasi-1] * tabelNk2[iterasi];
            } else if (ev[iterasi-1]=="x") {
                //isi bv
                bv1[iterasi]=bv1[iterasi-1];
                bv2[iterasi]="X";
                bv3[iterasi]=bv3[iterasi-1];
                bv4[iterasi]=bv4[iterasi-1];
                //baris 1
                tabelW1[iterasi] = tabelW1[iterasi-1] - tabelX1[iterasi-1] * tabelW2[iterasi];
                tabelZ1[iterasi] = tabelZ1[iterasi-1] - tabelX1[iterasi-1] * tabelZ2[iterasi];
                tabelX1[iterasi] = tabelX1[iterasi-1] - tabelX1[iterasi-1] * tabelX2[iterasi];
                tabelY1[iterasi] = tabelY1[iterasi-1] - tabelX1[iterasi-1] * tabelY2[iterasi];
                tabelS11[iterasi] =tabelS11[iterasi-1] - tabelX1[iterasi-1] * tabelS12[iterasi];
                tabelS21[iterasi] =tabelS21[iterasi-1] - tabelX1[iterasi-1] * tabelS22[iterasi];
                tabelS31[iterasi] =tabelS31[iterasi-1] - tabelX1[iterasi-1] * tabelS32[iterasi];
                tabelNk1[iterasi] =tabelNk1[iterasi-1] - tabelX1[iterasi-1] * tabelNk2[iterasi];
                //baris 3
                tabelW3[iterasi] = tabelW3[iterasi-1] - tabelX3[iterasi-1] * tabelW2[iterasi];
                tabelZ3[iterasi] = tabelZ3[iterasi-1] - tabelX3[iterasi-1] * tabelZ2[iterasi];
                tabelX3[iterasi] = tabelX3[iterasi-1] - tabelX3[iterasi-1] * tabelX2[iterasi];
                tabelY3[iterasi] = tabelY3[iterasi-1] - tabelX3[iterasi-1] * tabelY2[iterasi];
                tabelS13[iterasi] =tabelS13[iterasi-1] - tabelX3[iterasi-1] * tabelS12[iterasi];
                tabelS23[iterasi] =tabelS23[iterasi-1] - tabelX3[iterasi-1] * tabelS22[iterasi];
                tabelS33[iterasi] =tabelS33[iterasi-1] - tabelX3[iterasi-1] * tabelS32[iterasi];
                tabelNk3[iterasi] =tabelNk3[iterasi-1] - tabelX3[iterasi-1] * tabelNk2[iterasi];
                //baris 4
                tabelW4[iterasi] = tabelW4[iterasi-1] - tabelX4[iterasi-1] * tabelW2[iterasi];
                tabelZ4[iterasi] = tabelZ4[iterasi-1] - tabelX4[iterasi-1] * tabelZ2[iterasi];
                tabelX4[iterasi] = tabelX4[iterasi-1] - tabelX4[iterasi-1] * tabelX2[iterasi];
                tabelY4[iterasi] = tabelY4[iterasi-1] - tabelX4[iterasi-1] * tabelY2[iterasi];
                tabelS14[iterasi] =tabelS14[iterasi-1] - tabelX4[iterasi-1] * tabelS12[iterasi];
                tabelS24[iterasi] =tabelS24[iterasi-1] - tabelX4[iterasi-1] * tabelS22[iterasi];
                tabelS34[iterasi] =tabelS34[iterasi-1] - tabelX4[iterasi-1] * tabelS32[iterasi];
                tabelNk4[iterasi] =tabelNk4[iterasi-1] - tabelX4[iterasi-1] * tabelNk2[iterasi];
            } else if (ev[iterasi-1]=="y") {
                //isi bv
                bv1[iterasi]=bv1[iterasi-1];
                bv2[iterasi]="Y";
                bv3[iterasi]=bv3[iterasi-1];
                bv4[iterasi]=bv4[iterasi-1];
                //baris 1
                tabelW1[iterasi] = tabelW1[iterasi-1] - tabelY1[iterasi-1] * tabelW2[iterasi];
                tabelZ1[iterasi] = tabelZ1[iterasi-1] - tabelY1[iterasi-1] * tabelZ2[iterasi];
                tabelX1[iterasi] = tabelX1[iterasi-1] - tabelY1[iterasi-1] * tabelX2[iterasi];
                tabelY1[iterasi] = tabelY1[iterasi-1] - tabelY1[iterasi-1] * tabelY2[iterasi];
                tabelS11[iterasi] =tabelS11[iterasi-1] - tabelY1[iterasi-1] * tabelS12[iterasi];
                tabelS21[iterasi] =tabelS21[iterasi-1] - tabelY1[iterasi-1] * tabelS22[iterasi];
                tabelS31[iterasi] =tabelS31[iterasi-1] - tabelY1[iterasi-1] * tabelS32[iterasi];
                tabelNk1[iterasi] =tabelNk1[iterasi-1] - tabelY1[iterasi-1] * tabelNk2[iterasi];
                //baris 3
                tabelW3[iterasi] = tabelW3[iterasi-1] - tabelY3[iterasi-1] * tabelW2[iterasi];
                tabelZ3[iterasi] = tabelZ3[iterasi-1] - tabelY3[iterasi-1] * tabelZ2[iterasi];
                tabelX3[iterasi] = tabelX3[iterasi-1] - tabelY3[iterasi-1] * tabelX2[iterasi];
                tabelY3[iterasi] = tabelY3[iterasi-1] - tabelY3[iterasi-1] * tabelY2[iterasi];
                tabelS13[iterasi] =tabelS13[iterasi-1] - tabelY3[iterasi-1] * tabelS12[iterasi];
                tabelS23[iterasi] =tabelS23[iterasi-1] - tabelY3[iterasi-1] * tabelS22[iterasi];
                tabelS33[iterasi] =tabelS33[iterasi-1] - tabelY3[iterasi-1] * tabelS32[iterasi];
                tabelNk3[iterasi] =tabelNk3[iterasi-1] - tabelY3[iterasi-1] * tabelNk2[iterasi];
                //baris 4
                tabelW4[iterasi] = tabelW4[iterasi-1] - tabelY4[iterasi-1] * tabelW2[iterasi];
                tabelZ4[iterasi] = tabelZ4[iterasi-1] - tabelY4[iterasi-1] * tabelZ2[iterasi];
                tabelX4[iterasi] = tabelX4[iterasi-1] - tabelY4[iterasi-1] * tabelX2[iterasi];
                tabelY4[iterasi] = tabelY4[iterasi-1] - tabelY4[iterasi-1] * tabelY2[iterasi];
                tabelS14[iterasi] =tabelS14[iterasi-1] - tabelY4[iterasi-1] * tabelS12[iterasi];
                tabelS24[iterasi] =tabelS24[iterasi-1] - tabelY4[iterasi-1] * tabelS22[iterasi];
                tabelS34[iterasi] =tabelS34[iterasi-1] - tabelY4[iterasi-1] * tabelS32[iterasi];
                tabelNk4[iterasi] =tabelNk4[iterasi-1] - tabelY4[iterasi-1] * tabelNk2[iterasi];
            }
        } else if (lv[iterasi-1]=="3") {
            tabelZ3[iterasi]=barisPivot(tabelZ3[iterasi-1], iterasi);
            tabelW3[iterasi]=barisPivot(tabelW3[iterasi-1], iterasi);
            tabelX3[iterasi]=barisPivot(tabelX3[iterasi-1], iterasi);
            tabelY3[iterasi]=barisPivot(tabelY3[iterasi-1], iterasi);
            tabelS13[iterasi]=barisPivot(tabelS13[iterasi-1], iterasi);//salah di iterasi 1
            tabelS23[iterasi]=barisPivot(tabelS23[iterasi-1], iterasi);//salah di iterasi 1
            tabelS33[iterasi]=barisPivot(tabelS33[iterasi-1], iterasi);
            tabelNk3[iterasi]=barisPivot(tabelNk3[iterasi-1], iterasi);
            //baris non pivot
            if (ev[iterasi-1]=="w") {
                //isi bv
                bv1[iterasi]=bv1[iterasi-1];
                bv2[iterasi]=bv2[iterasi-1];
                bv3[iterasi]="W";
                bv4[iterasi]=bv4[iterasi-1];
                //baris 1
                tabelW1[iterasi] = tabelW1[iterasi-1] - tabelW1[iterasi-1] * tabelW3[iterasi];
                tabelZ1[iterasi] = tabelZ1[iterasi-1] - tabelW1[iterasi-1] * tabelZ3[iterasi];
                tabelX1[iterasi] = tabelX1[iterasi-1] - tabelW1[iterasi-1] * tabelX3[iterasi];
                tabelY1[iterasi] = tabelY1[iterasi-1] - tabelW1[iterasi-1] * tabelY3[iterasi];
                tabelS11[iterasi] =tabelS11[iterasi-1] - tabelW1[iterasi-1] * tabelS13[iterasi];
                tabelS21[iterasi] =tabelS21[iterasi-1] - tabelW1[iterasi-1] * tabelS23[iterasi];
                tabelS31[iterasi] =tabelS31[iterasi-1] - tabelW1[iterasi-1] * tabelS33[iterasi];
                tabelNk1[iterasi] =tabelNk1[iterasi-1] - tabelW1[iterasi-1] * tabelNk3[iterasi];
                //baris 2
                tabelW2[iterasi] = tabelW2[iterasi-1] - tabelW2[iterasi-1] * tabelW3[iterasi];
                tabelZ2[iterasi] = tabelZ2[iterasi-1] - tabelW2[iterasi-1] * tabelZ3[iterasi];
                tabelX2[iterasi] = tabelX2[iterasi-1] - tabelW2[iterasi-1] * tabelX3[iterasi];
                tabelY2[iterasi] = tabelY2[iterasi-1] - tabelW2[iterasi-1] * tabelY3[iterasi];
                tabelS12[iterasi] =tabelS12[iterasi-1] - tabelW2[iterasi-1] * tabelS13[iterasi];
                tabelS22[iterasi] =tabelS22[iterasi-1] - tabelW2[iterasi-1] * tabelS23[iterasi];
                tabelS32[iterasi] =tabelS32[iterasi-1] - tabelW2[iterasi-1] * tabelS33[iterasi];
                tabelNk2[iterasi] =tabelNk2[iterasi-1] - tabelW2[iterasi-1] * tabelNk3[iterasi];
                //baris 4
                tabelW4[iterasi] = tabelW4[iterasi-1] - tabelW4[iterasi-1] * tabelW3[iterasi];
                tabelZ4[iterasi] = tabelZ4[iterasi-1] - tabelW4[iterasi-1] * tabelZ3[iterasi];
                tabelX4[iterasi] = tabelX4[iterasi-1] - tabelW4[iterasi-1] * tabelX3[iterasi];
                tabelY4[iterasi] = tabelY4[iterasi-1] - tabelW4[iterasi-1] * tabelY3[iterasi];
                tabelS14[iterasi] =tabelS14[iterasi-1] - tabelW4[iterasi-1] * tabelS13[iterasi];
                tabelS24[iterasi] =tabelS24[iterasi-1] - tabelW4[iterasi-1] * tabelS23[iterasi];
                tabelS34[iterasi] =tabelS34[iterasi-1] - tabelW4[iterasi-1] * tabelS33[iterasi];
                tabelNk4[iterasi] =tabelNk4[iterasi-1] - tabelW4[iterasi-1] * tabelNk3[iterasi];
            } else if (ev[iterasi-1]=="x") {
                //isi bv
                bv1[iterasi]=bv1[iterasi-1];
                bv2[iterasi]=bv2[iterasi-1];
                bv3[iterasi]="X";
                bv4[iterasi]=bv4[iterasi-1];
                //baris 1
                tabelW1[iterasi] = tabelW1[iterasi-1] - tabelX1[iterasi-1] * tabelW3[iterasi];
                tabelZ1[iterasi] = tabelZ1[iterasi-1] - tabelX1[iterasi-1] * tabelZ3[iterasi];
                tabelX1[iterasi] = tabelX1[iterasi-1] - tabelX1[iterasi-1] * tabelX3[iterasi];
                tabelY1[iterasi] = tabelY1[iterasi-1] - tabelX1[iterasi-1] * tabelY3[iterasi];
                tabelS11[iterasi] =tabelS11[iterasi-1] - tabelX1[iterasi-1] * tabelS13[iterasi];
                tabelS21[iterasi] =tabelS21[iterasi-1] - tabelX1[iterasi-1] * tabelS23[iterasi];
                tabelS31[iterasi] =tabelS31[iterasi-1] - tabelX1[iterasi-1] * tabelS33[iterasi];
                tabelNk1[iterasi] =tabelNk1[iterasi-1] - tabelX1[iterasi-1] * tabelNk3[iterasi];
                //baris 2
                tabelW2[iterasi] = tabelW2[iterasi-1] - tabelX2[iterasi-1] * tabelW3[iterasi];
                tabelZ2[iterasi] = tabelZ2[iterasi-1] - tabelX2[iterasi-1] * tabelZ3[iterasi];
                tabelX2[iterasi] = tabelX2[iterasi-1] - tabelX2[iterasi-1] * tabelX3[iterasi];
                tabelY2[iterasi] = tabelY2[iterasi-1] - tabelX2[iterasi-1] * tabelY3[iterasi];
                tabelS12[iterasi] =tabelS12[iterasi-1] - tabelX2[iterasi-1] * tabelS13[iterasi];
                tabelS22[iterasi] =tabelS22[iterasi-1] - tabelX2[iterasi-1] * tabelS23[iterasi];
                tabelS32[iterasi] =tabelS32[iterasi-1] - tabelX2[iterasi-1] * tabelS33[iterasi];
                tabelNk2[iterasi] =tabelNk2[iterasi-1] - tabelX2[iterasi-1] * tabelNk3[iterasi];
                //baris 4
                tabelW4[iterasi] = tabelW4[iterasi-1] - tabelX4[iterasi-1] * tabelW3[iterasi];
                tabelZ4[iterasi] = tabelZ4[iterasi-1] - tabelX4[iterasi-1] * tabelZ3[iterasi];
                tabelX4[iterasi] = tabelX4[iterasi-1] - tabelX4[iterasi-1] * tabelX3[iterasi];
                tabelY4[iterasi] = tabelY4[iterasi-1] - tabelX4[iterasi-1] * tabelY3[iterasi];
                tabelS14[iterasi] =tabelS14[iterasi-1] - tabelX4[iterasi-1] * tabelS13[iterasi];
                tabelS24[iterasi] =tabelS24[iterasi-1] - tabelX4[iterasi-1] * tabelS23[iterasi];
                tabelS34[iterasi] =tabelS34[iterasi-1] - tabelX4[iterasi-1] * tabelS33[iterasi];
                tabelNk4[iterasi] =tabelNk4[iterasi-1] - tabelX4[iterasi-1] * tabelNk3[iterasi];
            } else if (ev[iterasi-1]=="y") {
                //isi bv
                bv1[iterasi]=bv1[iterasi-1];
                bv2[iterasi]=bv2[iterasi-1];
                bv3[iterasi]="Y";
                bv4[iterasi]=bv4[iterasi-1];
                //baris 1
                tabelW1[iterasi] = tabelW1[iterasi-1] - tabelY1[iterasi-1] * tabelW3[iterasi];
                tabelZ1[iterasi] = tabelZ1[iterasi-1] - tabelY1[iterasi-1] * tabelZ3[iterasi];
                tabelX1[iterasi] = tabelX1[iterasi-1] - tabelY1[iterasi-1] * tabelX3[iterasi];
                tabelY1[iterasi] = tabelY1[iterasi-1] - tabelY1[iterasi-1] * tabelY3[iterasi];
                tabelS11[iterasi] =tabelS11[iterasi-1] - tabelY1[iterasi-1] * tabelS13[iterasi];
                tabelS21[iterasi] =tabelS21[iterasi-1] - tabelY1[iterasi-1] * tabelS23[iterasi];
                tabelS31[iterasi] =tabelS31[iterasi-1] - tabelY1[iterasi-1] * tabelS33[iterasi];
                tabelNk1[iterasi] =tabelNk1[iterasi-1] - tabelY1[iterasi-1] * tabelNk3[iterasi];
                //baris 2
                tabelW2[iterasi] = tabelW2[iterasi-1] - tabelY2[iterasi-1] * tabelW3[iterasi];
                tabelZ2[iterasi] = tabelZ2[iterasi-1] - tabelY2[iterasi-1] * tabelZ3[iterasi];
                tabelX2[iterasi] = tabelX2[iterasi-1] - tabelY2[iterasi-1] * tabelX3[iterasi];
                tabelY2[iterasi] = tabelY2[iterasi-1] - tabelY2[iterasi-1] * tabelY3[iterasi];
                tabelS12[iterasi] =tabelS12[iterasi-1] - tabelY2[iterasi-1] * tabelS13[iterasi];
                tabelS22[iterasi] =tabelS22[iterasi-1] - tabelY2[iterasi-1] * tabelS23[iterasi];//salah di iterasi 1
                tabelS32[iterasi] =tabelS32[iterasi-1] - tabelY2[iterasi-1] * tabelS33[iterasi];//salah di iterasi 1
                tabelNk2[iterasi] =tabelNk2[iterasi-1] - tabelY2[iterasi-1] * tabelNk3[iterasi];
                //baris 4
                tabelW4[iterasi] = tabelW4[iterasi-1] - tabelY4[iterasi-1] * tabelW3[iterasi];
                tabelZ4[iterasi] = tabelZ4[iterasi-1] - tabelY4[iterasi-1] * tabelZ3[iterasi];
                tabelX4[iterasi] = tabelX4[iterasi-1] - tabelY4[iterasi-1] * tabelX3[iterasi];
                tabelY4[iterasi] = tabelY4[iterasi-1] - tabelY4[iterasi-1] * tabelY3[iterasi];
                tabelS14[iterasi] =tabelS14[iterasi-1] - tabelY4[iterasi-1] * tabelS13[iterasi];//salah di iterasi 1
                tabelS24[iterasi] =tabelS24[iterasi-1] - tabelY4[iterasi-1] * tabelS23[iterasi];//salah di iterasi 1
                tabelS34[iterasi] =tabelS34[iterasi-1] - tabelY4[iterasi-1] * tabelS33[iterasi];//salah di iterasi 1
                tabelNk4[iterasi] =tabelNk4[iterasi-1] - tabelY4[iterasi-1] * tabelNk3[iterasi];
            }
        } else if (lv[iterasi-1]=="4") {
            tabelZ4[iterasi]=barisPivot(tabelZ4[iterasi-1], iterasi);
            tabelW4[iterasi]=barisPivot(tabelW4[iterasi-1], iterasi);//salah di iterasi 2
            tabelX4[iterasi]=barisPivot(tabelX4[iterasi-1], iterasi);
            tabelY4[iterasi]=barisPivot(tabelY4[iterasi-1], iterasi);
            tabelS14[iterasi]=barisPivot(tabelS14[iterasi-1], iterasi);
            tabelS24[iterasi]=barisPivot(tabelS24[iterasi-1], iterasi);//salah di iterasi 2
            tabelS34[iterasi]=barisPivot(tabelS34[iterasi-1], iterasi);//salah di iterasi 2
            tabelNk4[iterasi]=barisPivot(tabelNk4[iterasi-1], iterasi);
            //baris non pivot
            if (ev[iterasi-1]=="w") {
                //isi bv
                bv1[iterasi]=bv1[iterasi-1];
                bv2[iterasi]=bv2[iterasi-1];
                bv3[iterasi]=bv3[iterasi-1];
                bv4[iterasi]="W";
                //baris 1
                tabelW1[iterasi] = tabelW1[iterasi-1] - tabelW1[iterasi-1] * tabelW4[iterasi];
                tabelZ1[iterasi] = tabelZ1[iterasi-1] - tabelW1[iterasi-1] * tabelZ4[iterasi];
                tabelX1[iterasi] = tabelX1[iterasi-1] - tabelW1[iterasi-1] * tabelX4[iterasi];
                tabelY1[iterasi] = tabelY1[iterasi-1] - tabelW1[iterasi-1] * tabelY4[iterasi];
                tabelS11[iterasi] =tabelS11[iterasi-1] - tabelW1[iterasi-1] * tabelS14[iterasi];
                tabelS21[iterasi] =tabelS21[iterasi-1] - tabelW1[iterasi-1] * tabelS24[iterasi];
                tabelS31[iterasi] =tabelS31[iterasi-1] - tabelW1[iterasi-1] * tabelS34[iterasi];
                tabelNk1[iterasi] =tabelNk1[iterasi-1] - tabelW1[iterasi-1] * tabelNk4[iterasi];
                //baris 2
                tabelW2[iterasi] = tabelW2[iterasi-1] - tabelW2[iterasi-1] * tabelW4[iterasi];
                tabelZ2[iterasi] = tabelZ2[iterasi-1] - tabelW2[iterasi-1] * tabelZ4[iterasi];
                tabelX2[iterasi] = tabelX2[iterasi-1] - tabelW2[iterasi-1] * tabelX4[iterasi];
                tabelY2[iterasi] = tabelY2[iterasi-1] - tabelW2[iterasi-1] * tabelY4[iterasi];
                tabelS12[iterasi] =tabelS12[iterasi-1] - tabelW2[iterasi-1] * tabelS14[iterasi];
                tabelS22[iterasi] =tabelS22[iterasi-1] - tabelW2[iterasi-1] * tabelS24[iterasi];
                tabelS32[iterasi] =tabelS32[iterasi-1] - tabelW2[iterasi-1] * tabelS34[iterasi];
                tabelNk2[iterasi] =tabelNk2[iterasi-1] - tabelW2[iterasi-1] * tabelNk4[iterasi];
                //baris 3
                tabelW3[iterasi] = tabelW3[iterasi-1] - tabelW3[iterasi-1] * tabelW4[iterasi];
                tabelZ3[iterasi] = tabelZ3[iterasi-1] - tabelW3[iterasi-1] * tabelZ4[iterasi];
                tabelX3[iterasi] = tabelX3[iterasi-1] - tabelW3[iterasi-1] * tabelX4[iterasi];
                tabelY3[iterasi] = tabelY3[iterasi-1] - tabelW3[iterasi-1] * tabelY4[iterasi];
                tabelS13[iterasi] =tabelS13[iterasi-1] - tabelW3[iterasi-1] * tabelS14[iterasi];
                tabelS23[iterasi] =tabelS23[iterasi-1] - tabelW3[iterasi-1] * tabelS24[iterasi];
                tabelS33[iterasi] =tabelS33[iterasi-1] - tabelW3[iterasi-1] * tabelS34[iterasi];
                tabelNk3[iterasi] =tabelNk3[iterasi-1] - tabelW3[iterasi-1] * tabelNk4[iterasi];
            } else if (ev[iterasi-1]=="x") {
                //isi bv
                bv1[iterasi]=bv1[iterasi-1];
                bv2[iterasi]=bv2[iterasi-1];
                bv3[iterasi]=bv3[iterasi-1];
                bv4[iterasi]="X";
                //baris 1
                tabelW1[iterasi] = tabelW1[iterasi-1] - tabelX1[iterasi-1] * tabelW4[iterasi];
                tabelZ1[iterasi] = tabelZ1[iterasi-1] - tabelX1[iterasi-1] * tabelZ4[iterasi];
                tabelX1[iterasi] = tabelX1[iterasi-1] - tabelX1[iterasi-1] * tabelX4[iterasi];
                tabelY1[iterasi] = tabelY1[iterasi-1] - tabelX1[iterasi-1] * tabelY4[iterasi];
                tabelS11[iterasi] =tabelS11[iterasi-1] - tabelX1[iterasi-1] * tabelS14[iterasi];
                tabelS21[iterasi] =tabelS21[iterasi-1] - tabelX1[iterasi-1] * tabelS24[iterasi];
                tabelS31[iterasi] =tabelS31[iterasi-1] - tabelX1[iterasi-1] * tabelS34[iterasi];
                tabelNk1[iterasi] =tabelNk1[iterasi-1] - tabelX1[iterasi-1] * tabelNk4[iterasi];
                //baris 2
                tabelW2[iterasi] = tabelW2[iterasi-1] - tabelX2[iterasi-1] * tabelW4[iterasi];
                tabelZ2[iterasi] = tabelZ2[iterasi-1] - tabelX2[iterasi-1] * tabelZ4[iterasi];
                tabelX2[iterasi] = tabelX2[iterasi-1] - tabelX2[iterasi-1] * tabelX4[iterasi];
                tabelY2[iterasi] = tabelY2[iterasi-1] - tabelX2[iterasi-1] * tabelY4[iterasi];
                tabelS12[iterasi] =tabelS12[iterasi-1] - tabelX2[iterasi-1] * tabelS14[iterasi];
                tabelS22[iterasi] =tabelS22[iterasi-1] - tabelX2[iterasi-1] * tabelS24[iterasi];
                tabelS32[iterasi] =tabelS32[iterasi-1] - tabelX2[iterasi-1] * tabelS34[iterasi];
                tabelNk2[iterasi] =tabelNk2[iterasi-1] - tabelX2[iterasi-1] * tabelNk4[iterasi];
                //baris 3
                tabelW3[iterasi] = tabelW3[iterasi-1] - tabelX3[iterasi-1] * tabelW4[iterasi];
                tabelZ3[iterasi] = tabelZ3[iterasi-1] - tabelX3[iterasi-1] * tabelZ4[iterasi];
                tabelX3[iterasi] = tabelX3[iterasi-1] - tabelX3[iterasi-1] * tabelX4[iterasi];
                tabelY3[iterasi] = tabelY3[iterasi-1] - tabelX3[iterasi-1] * tabelY4[iterasi];
                tabelS13[iterasi] =tabelS13[iterasi-1] - tabelX3[iterasi-1] * tabelS14[iterasi];
                tabelS23[iterasi] =tabelS23[iterasi-1] - tabelX3[iterasi-1] * tabelS24[iterasi];
                tabelS33[iterasi] =tabelS33[iterasi-1] - tabelX3[iterasi-1] * tabelS34[iterasi];
                tabelNk3[iterasi] =tabelNk3[iterasi-1] - tabelX3[iterasi-1] * tabelNk4[iterasi];
            } else if (ev[iterasi-1]=="y") {
                //isi bv
                bv1[iterasi]=bv1[iterasi-1];
                bv2[iterasi]=bv2[iterasi-1];
                bv3[iterasi]=bv3[iterasi-1];
                bv4[iterasi]="Y";
                //baris 1
                tabelW1[iterasi] = tabelW1[iterasi-1] - tabelY1[iterasi-1] * tabelW4[iterasi];//salah di iterasi 2
                tabelZ1[iterasi] = tabelZ1[iterasi-1] - tabelY1[iterasi-1] * tabelZ4[iterasi];
                tabelX1[iterasi] = tabelX1[iterasi-1] - tabelY1[iterasi-1] * tabelX4[iterasi];
                tabelY1[iterasi] = tabelY1[iterasi-1] - tabelY1[iterasi-1] * tabelY4[iterasi];
                tabelS11[iterasi] =tabelS11[iterasi-1] - tabelY1[iterasi-1] * tabelS14[iterasi];
                tabelS21[iterasi] =tabelS21[iterasi-1] - tabelY1[iterasi-1] * tabelS24[iterasi];//salah di iterasi 2
                tabelS31[iterasi] =tabelS31[iterasi-1] - tabelY1[iterasi-1] * tabelS34[iterasi];//salah di iterasi 2
                tabelNk1[iterasi] =tabelNk1[iterasi-1] - tabelY1[iterasi-1] * tabelNk4[iterasi];
                //baris 2
                tabelW2[iterasi] = tabelW2[iterasi-1] - tabelY2[iterasi-1] * tabelW4[iterasi];//salah di iterasi 2
                tabelZ2[iterasi] = tabelZ2[iterasi-1] - tabelY2[iterasi-1] * tabelZ4[iterasi];
                tabelX2[iterasi] = tabelX2[iterasi-1] - tabelY2[iterasi-1] * tabelX4[iterasi];
                tabelY2[iterasi] = tabelY2[iterasi-1] - tabelY2[iterasi-1] * tabelY4[iterasi];
                tabelS12[iterasi] =tabelS12[iterasi-1] - tabelY2[iterasi-1] * tabelS14[iterasi];
                tabelS22[iterasi] =tabelS22[iterasi-1] - tabelY2[iterasi-1] * tabelS24[iterasi];//salah di iterasi 2
                tabelS32[iterasi] =tabelS32[iterasi-1] - tabelY2[iterasi-1] * tabelS34[iterasi];//salah di iterasi 2
                tabelNk2[iterasi] =tabelNk2[iterasi-1] - tabelY2[iterasi-1] * tabelNk4[iterasi];
                //baris 3
                tabelW3[iterasi] = tabelW3[iterasi-1] - tabelY3[iterasi-1] * tabelW4[iterasi];//salah di iterasi 2
                tabelZ3[iterasi] = tabelZ3[iterasi-1] - tabelY3[iterasi-1] * tabelZ4[iterasi];
                tabelX3[iterasi] = tabelX3[iterasi-1] - tabelY3[iterasi-1] * tabelX4[iterasi];
                tabelY3[iterasi] = tabelY3[iterasi-1] - tabelY3[iterasi-1] * tabelY4[iterasi];
                tabelS13[iterasi] =tabelS13[iterasi-1] - tabelY3[iterasi-1] * tabelS14[iterasi];
                tabelS23[iterasi] =tabelS23[iterasi-1] - tabelY3[iterasi-1] * tabelS24[iterasi];//salah di iterasi 2
                tabelS33[iterasi] =tabelS33[iterasi-1] - tabelY3[iterasi-1] * tabelS34[iterasi];//salah di iterasi 2
                tabelNk3[iterasi] =tabelNk3[iterasi-1] - tabelY3[iterasi-1] * tabelNk4[iterasi];
            }
        }
    }
    
    private float barisPivot(float nilaiItem, int iterasi){
        return (nilaiItem/pivot[iterasi-1]);
    }
    private float barisNonPivot(float nilaiItem, float nilaiItemKolomPivot,float nilaiItemBarisPivot){
        return (nilaiItem - nilaiItemKolomPivot * nilaiItemBarisPivot);
    }

    private void hitungTabelSimplex() {
        //iterasi perhitungan metode simplex
        int i = 0;
        do {
            if (i==0) {
                iterasiNol();
            }else{
                //selain iterasi nol
                operasiBaris(i);
            }
            //update isi tabel
            updateIsiTabel(i);
            //masukan nilai langkah iterasi
            iterasi=i;
            tf_iterasi.setText(iterasi+"");
            cariPivot(i);
            tf_pivot.setText(pivot[i]+"");
            i++;
        } while (pivot[i-1]!=0);
    }

    private void tampilkanHasil() {
        //menampilkan nilai hasil
        tf_hasil_z.setText(tabelNk1[iterasi]+"");
        ambilNkDariBv(bv2[iterasi], 2);
        ambilNkDariBv(bv3[iterasi], 3);
        ambilNkDariBv(bv4[iterasi], 4);
    }

    private void ambilNkDariBv(String isiBv, int baris) {
        if (baris==2) {
            if (isiBv=="W") {
                tf_hasil_w.setText(tabelNk2[iterasi]+"");
            }else if (isiBv=="X") {
                tf_hasil_x.setText(tabelNk2[iterasi]+"");
            }else if (isiBv=="Y") {
                tf_hasil_y.setText(tabelNk2[iterasi]+"");
            }else if (isiBv=="s1") {
                tf_hasil_s1.setText(tabelNk2[iterasi]+"");
            }else if (isiBv=="s2") {
                tf_hasil_s2.setText(tabelNk2[iterasi]+"");
            }else if (isiBv=="s3") {
                tf_hasil_s3.setText(tabelNk2[iterasi]+"");
            }
        }else if (baris==3) {
            if (isiBv=="W") {
                tf_hasil_w.setText(tabelNk3[iterasi]+"");
            }else if (isiBv=="X") {
                tf_hasil_x.setText(tabelNk3[iterasi]+"");
            }else if (isiBv=="Y") {
                tf_hasil_y.setText(tabelNk3[iterasi]+"");
            }else if (isiBv=="s1") {
                tf_hasil_s1.setText(tabelNk3[iterasi]+"");
            }else if (isiBv=="s2") {
                tf_hasil_s2.setText(tabelNk3[iterasi]+"");
            }else if (isiBv=="s3") {
                tf_hasil_s3.setText(tabelNk3[iterasi]+"");
            }
        }else if (baris==4) {
            if (isiBv=="W") {
                tf_hasil_w.setText(tabelNk4[iterasi]+"");
            }else if (isiBv=="X") {
                tf_hasil_x.setText(tabelNk4[iterasi]+"");
            }else if (isiBv=="Y") {
                tf_hasil_y.setText(tabelNk4[iterasi]+"");
            }else if (isiBv=="s1") {
                tf_hasil_s1.setText(tabelNk4[iterasi]+"");
            }else if (isiBv=="s2") {
                tf_hasil_s2.setText(tabelNk4[iterasi]+"");
            }else if (isiBv=="s3") {
                tf_hasil_s3.setText(tabelNk4[iterasi]+"");
            }
        }
    }
}
